name: Manual Android Build
on:
  workflow_dispatch:

env:
  # Ensuring we use the 2026-standard Node runtime for actions
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        # This builds the universal debug APK
        run: ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ytdlnis-debug-apk
          # Path where Gradle outputs the APK
          path: app/build/outputs/apk/debug/*.apk
